module.exports = [
  {
    name: "Azalea Hall",
    location: "West Jefferson St",
    capacity: 433,
    year: 2017,
    floors: 6,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/azalea",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/azalea/azalea.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/azalea/azalea4.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/azalea/azalea6.jpg",
    ],
  },
  {
    name: "Broward Hall",
    location: "University Way",
    capacity: 135,
    year: 1917,
    floors: 4,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/broward",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/broward/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/broward/7.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/broward/IMG_4920.JPG",
    ],
  },
  {
    name: "Bryan Hall",
    location: "Convocation Way",
    capacity: 131,
    year: 1907,
    floors: 3,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/bryan",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/bryan/3.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/bryan/7.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/bryan/IMG_5062.JPG",
    ],
  },
  {
    name: "Cawthon Hall",
    location: "Honors Way",
    capacity: 297,
    year: 1949,
    floors: 4,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/cawthon",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/cawthon/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/cawthon/caw_3.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/cawthon/IMG_5077.JPG",
    ],
  },
  {
    name: "Degraff Hall",
    location: "West Tennessee St",
    capacity: 706,
    year: 1950,
    floors: 5,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/degraff",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/degraff/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/degraff/6.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/degraff/IMG_4604.JPG",
    ],
  },
  {
    name: "Dorman Hall",
    location: "South Woodward Avenue",
    capacity: 433,
    year: 2015,
    floors: 6,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/dorman",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/dorman/dorman.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/dorman/dorman4.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/dorman/IMG_4710.JPG",
    ],
  },
  {
    name: "Deviney Hall",
    location: "South Woodward Avenue",
    capacity: 433,
    year: 2015,
    floors: 6,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/deviney",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/deviney/deviney.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/deviney/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/deviney/IMG_4643.JPG",
    ],
  },
  {
    name: "Gilchrist Hall",
    location: "University Way",
    capacity: 229,
    year: 1925,
    floors: 5,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/gilchrist",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/gilchrist/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/gilchrist/6.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/gilchrist/IMG_4832.JPG",
    ],
  },
  {
    name: "Jennie Murphree Hall",
    location: "Convocation Way",
    capacity: 328,
    year: 1921,
    floors: 4,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/jennie-murphree",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/jennieMurphree/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/jennieMurphree/5.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/jennieMurphree/IMG_5011.JPG",
    ],
  },
  {
    name: "Landis Hall",
    location: "University Way",
    capacity: 403,
    year: 1935,
    floors: 5,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/landis",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/landis/landis03_large.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/landis/13.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/landis/IMG_4787.JPG",
    ],
  },
  {
    name: "Magnolia Hall",
    location: "University Way",
    capacity: 479,
    year: 2017,
    floors: 4,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/magnolia",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/magnolia/magnolia.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/magnolia/magnolia3.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/magnolia/magnolia7.jpg",
    ],
  },
  {
    name: "Reynolds Hall",
    location: "Convocation Way",
    capacity: 239,
    year: 1911,
    floors: 4,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/reynolds",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/reynolds/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/reynolds/IMG_4920.JPG",
      "https://housing.fsu.edu/_img/residencyHalls/reynolds/IMG_4980.JPG",
    ],
  },
  {
    name: "Salley Hall",
    location: "West Call St",
    capacity: 570,
    year: 1964,
    floors: 8,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/salley",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/salley/Salley_large.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/salley/salley7.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/salley/IMG_5130.JPG",
    ],
  },
  {
    name: "Wildwood Hall",
    location: "West Jefferson St & Varsity Dr",
    capacity: 706,
    year: 2007,
    floors: 5,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/wildwood",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/wildwood/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/wildwood/IMG_4709.JPG",
      "https://housing.fsu.edu/_img/residencyHalls/wildwood/IMG_4726.JPG",
    ],
  },
  {
    name: "McCollum Hall",
    location: "Academic Way",
    capacity: 196,
    year: 1975,
    floors: 6,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/mccollum",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/mccollum/2.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/mccollum/IMG_5344.JPG",
      "https://housing.fsu.edu/_img/residencyHalls/mccollum/IMG_5380.JPG",
    ],
  },
  {
    name: "Ragans Hall",
    location: "Learning Way",
    capacity: 555,
    year: 2003,
    floors: 4,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/ragans",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/ragans/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/ragans/IMG_5454.JPG",
      "https://housing.fsu.edu/_img/residencyHalls/ragans/IMG_5483.JPG",
    ],
  },
  {
    name: "Rogers Hall",
    location: "Academic Way",
    capacity: 184,
    year: 1965,
    floors: 8,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/rogers",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/rogers/Rogers-Hall.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/rogers/IMG_5223.JPG",
      "https://housing.fsu.edu/_img/residencyHalls/rogers/IMG_5185.JPG",
    ],
  },
  {
    name: "Traditions Hall",
    location: "Learning Way",
    capacity: 276,
    year: 2012,
    floors: 5,
    review: 0,
    link: "https://housing.fsu.edu/future-residents/residence-halls#/traditions",
    image: [
      "https://housing.fsu.edu/_img/residencyHalls/traditions/1.jpg",
      "https://housing.fsu.edu/_img/residencyHalls/traditions/IMG_5499.JPG",
      "https://housing.fsu.edu/_img/residencyHalls/traditions/IMG_5561.JPG",
    ],
  },
];
